/*
 * 注册vant组件
 * 按需引入，自行在此处添加
 */

import Vue from 'vue';
import {
  // ActionSheet,
  // AddressList,
  // Button,
  // Card,
  // Cell,
  // CellGroup,
  // Circle,
  // Col,
  // Collapse,
  // CollapseItem,
  // ContactCard,
  // ContactEdit,
  // ContactList,
  // CouponCell,
  // CouponList,
  // Divider,
  // DropdownMenu,
  // Empty,
  // Grid,
  // GridItem,
  // GoodsAction,
  // GoodsActionButton,
  // GoodsActionIcon,
  Icon,
  // Image,
  // IndexAnchor,
  // IndexBar,
  // Info,
  // Loading,
  NavBar,
  // NoticeBar,
  // NumberKeyboard,
  // Overlay,
  // Pagination,
  // Panel,
  // PasswordInput,
  // Popup,
  // Progress,
  // PullRefresh,
  // Radio,
  // RadioGroup,
  // Rate,
  // Row,
  // Search,
  // ShareSheet,
  // Sidebar,
  // SidebarItem,
  // Skeleton,
  // Slider,
  // Step,
  // Stepper,
  // Steps,
  // Sticky,
  // SubmitBar,
  // SwipeItem,
  // Switch,
  // SwitchCell,
  // Tab,
  Tabbar,
  TabbarItem,
  // Tag,
  // TreeSelect,
} from 'vant';

const components = [
  // ActionSheet,
  // AddressList,
  // Button,
  // Card,
  // Cell,
  // CellGroup,
  // Circle,
  // Col,
  // Collapse,
  // CollapseItem,
  // ContactCard,
  // ContactEdit,
  // ContactList,
  // CouponCell,
  // CouponList,
  // Divider,
  // DropdownMenu,
  // Empty,
  // Grid,
  // GridItem,
  // GoodsAction,
  // GoodsActionButton,
  // GoodsActionIcon,
  Icon,
  // Image,
  // IndexAnchor,
  // IndexBar,
  // Info,
  // Loading,
  NavBar,
  // NoticeBar,
  // NumberKeyboard,
  // Overlay,
  // Pagination,
  // Panel,
  // PasswordInput,
  // Popup,
  // Progress,
  // PullRefresh,
  // Radio,
  // RadioGroup,
  // Rate,
  // Row,
  // Search,
  // ShareSheet,
  // Sidebar,
  // SidebarItem,
  // Skeleton,
  // Slider,
  // Step,
  // Stepper,
  // Steps,
  // Sticky,
  // SubmitBar,
  // SwipeItem,
  // Switch,
  // SwitchCell,
  // Tab,
  Tabbar,
  TabbarItem,
  // Tag,
  // TreeSelect,
];

components.forEach((item) => {
  Vue.use(item);
});

// 挂载组件
// Vue.prototype.$message = message;

// 全局配置
// message
// message.config({
//   top: '88px',
//   duration: 2.5,
// });
